### ISSUE TITLE
Stack not found

### ISSUE THREAD

**Issue by mgarciadelojo** [jeremydaly/serverless-cloudside-plugin#3]
Hi,

First of all, thank you very much for this plugin. Hope it helps a lot of people making their lives easier when developing using Serverless Framework.

I've been trying to set up the plugin following the instructions, and unfortunately I get an error when running `serverless offline`.

Here the output:

```
$ SLS_DEBUG=true sls offline cloudside --port 3000 --host 0.0.0.0
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command invoke
Serverless: Load command invoke:cloudside
Serverless: Load command invoke:test
Serverless: Load command invoke:test:cloudside
Serverless: Load command offline
Serverless: Load command offline:cloudside
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke offline:cloudside
Serverless: Loading cloudside resources for 'learning-aws-local' stack.
Serverless: [AWS cloudformation 400 0.426s 0 retries] describeStackResources({ StackName: 'learning-aws-local' })
 
  Serverless Error ---------------------------------------
 
  Stack with id learning-aws-local does not exist
 
  Stack Trace --------------------------------------------
 
ServerlessError: Stack with id learning-aws-local does not exist
    at promise.catch.err (/app/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           10.16.0
     Serverless Version:     1.44.1
```

Does anyone know what I am doing wrong?

My `serverless.yml` is quite simple:

```
service: learning-aws
frameworkVersion: "=1.44.1"

provider:
  name: aws
  runtime: nodejs10.x
  stage: local
  region: eu-west-1
  stackName: learning-aws-local

plugins:
  - serverless-cloudside-plugin
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk
    excludeFiles: handlers/**/*.test.js

functions:
  create-request:
    handler: handlers/create-request/index.handler
    environment:
      QUEUE: !Ref myQueue
    events:
      - http:
         path: requests
         method: post

resources:
  Resources:
    myQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-myQueue

```
