### ISSUE TITLE
!Ref AWS:AccountId returns 'RESOURCE NOT PUBLISHED'

### ISSUE THREAD

**Issue by MattNguyen** [jeremydaly/serverless-cloudside-plugin#4]
Hi Jeremy,

Appreciate your work on this. I can see this being quite valuable but running into some roadblocks.

I'm attempting to construct an arn for an `AWS::RDS::DbCluster` which is passed to the environment of a lambda function.

Originally I was using serverless-pseudo-parameters to return a string like so :

```yaml
environment:
  DbClusterArn: "arn:aws:rds:${self:provider.region}:#{AWS::AccountId}:cluster:#{AuroraCluster}"
```
However it appears that serverless-pseudo-parameters + serverless-cloudside-plugin don't play well together.

So I broke out each parameter into a separate env var and constructed the arn in the lambda function: 

```yaml
environment:
  DbClusterId: !Ref AuroraCluster
  AccountId: !Ref "AWS::AccountId"
  Region: ${self:provider.region}
```
However the `AccountId` returns `<Resource Not Published>`.

My questions are:

1. Should this work nicely with serverless-pseudo-parameters?
2. Should refs to pseudo parameters work?
